# Имя workflow
name: Node.js App test

# Триггеры
on: [push, pull_request] # триггерится при пуше и пулл реквесте

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo Hello, world
      - name: Message about pushed commits
        run: |
          echo The commits had been pushed
          echo Success
